apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: "<Client ID of your User Managed Idnetity>"
    keyvaultName: "<your Azure Key Vault name>"
    cloudName: ""
    tenantId: "<Tenant ID>"
    objects: |
      array:
        - |
          objectName: CONNECTIONSTRING
          objectAlias: CONNECTION_STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: COSMOSDATABASENAME
          objectAlias: COSMOS_DATABASE_NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: USERCOLLECTIONNAME
          objectAlias: USER_COLLECTION_NAME
          objectType: secret
          objectVersion: ""
        - |
          objectName: ACTIVITYCOLLECTIONNAME
          objectAlias: ACTIVITY_COLLECTION_NAME
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: azure-keyvault-secrets
      type: Opaque
      data:
        - objectName: CONNECTION_STRING
          key: CONNECTION_STRING
        - objectName: COSMOS_DATABASE_NAME
          key: COSMOS_DATABASE_NAME
        - objectName: USER_COLLECTION_NAME
          key: USER_COLLECTION_NAME
        - objectName: ACTIVITY_COLLECTION_NAME
          key: ACTIVITY_COLLECTION_NAME
